### ISSUE TITLE
I have lots of images to detect, how can i track a particular image and play its corresponding video

### ISSUE THREAD

**Issue by KittuPatel** [BlackMirrorz/ARKitDynamicReferenceImages#1]
Hey BlackMirrorz! I can play videos of respective images when the AR Resources images are stored in the local resource group. But how do I dynamically detect an image from the cloud, if I have all the images in the resource group then it is not suitable.

**Comment by BlackMirrorz** [comment]
If you want to identify an image from the cloud you would need to use CoreML or the Vision Framework to start with. As such this isn’t really an issue with the actual code itself just an additional feature ^_______^.
